version: "3.1"
services:

    node:
        build:
            context: .
            dockerfile: docker/node/Dockerfile
        container_name: karaoke-app-node
        working_dir: /application
        ports:
            - "8081:8080"
